"""empty message

Revision ID: 9430248006fa
Revises: 099c9cc4b230
Create Date: 2023-06-22 22:09:46.949057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9430248006fa'
down_revision = '099c9cc4b230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
